name: Timed Clock In
on: 
  schedule:
    - cron: '47 3,5 * * *'

jobs:
  Clock-In:
    runs-on: ubuntu-20.04
    env:
      user_account: ${{ secrets.USER_ACCOUNT }}
      user_password: ${{ secrets.USER_PASSWORD }}
    steps:
      - name: Install necessary tools
        run: sudo apt install python3.9 python3-requests
      - name: Check out repo code
        uses: actions/checkout@v3
      - name: Clock in
        run: python3 ${{ github.workspace }}/main.py --account $user_account --password $user_password
